# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
builds:
  - dir: ../
    targets:
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -X 'github.com/trilogy-group/cloudfix-linter-developer/cmd.Version={{ .Env.CLI_VERSION }}'
archives:
  - id: zip
    name_template: "{{ .Env.APP_NAME }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    files:
      - install.sh
      - install.ps1
checksum:
  name_template: 'checksums.txt'